data_ingestion:
  bucket_name: "to_learn_bucket_1"
  bucket_file_name : "hotel_reservations/hotel_reservations.csv"
  train_ratio: 0.8


data_processing:
  categorilcal_columns:
    - type_of_meal_plan
    - room_type_reserved
    - market_segment_type
    - booking_status
    

  numerical_columns:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - required_car_parking_space
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - repeated_guest
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests

  skewness_threshold : 5
  number_of_selected_features : 10